// Create a new transaction

POST http://localhost:3333/transactions
Content-Type: application/json

{
    "title": "Event A",
    "amount": 100,
    "type": "deposit"
}

###
// List all transactions
GET http://localhost:3333/transactions

###
// Get a transaction by ID
GET http://localhost:3333/transactions/dbfadfa0-71ed-4256-977e-8c94135ff186